language:
  - node_js

node_js:
  - '8'

services:
  - postgresql

addons:
  postgresql: '9.6'

env:
  global:
    - NODE_ENV=test
    - export DATABASE_TEST_URL=postgresql://localhost/linr_db_test

before_script:
  - psql -c 'create database linr_db_test;' -U postgres

script:
  - npm run test
